name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: ruff check .
      - name: Tests
        run: pytest -q
      - name: Quick training smoke (v0.1)
        run: python -m training.train --version v0.1
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: models-and-metrics
          path: models/
  docker-build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build -t clinic-triage:ci .
      - name: Smoke container
        run: |
          docker run -d -p 8000:8000 --name svc clinic-triage:ci
          sleep 3
          curl -s http://localhost:8000/health | grep '"status":"ok"'
          curl -s -X POST http://localhost:8000/predict -H "Content-Type: application/json" -d '{"age":0.02,"sex":-0.044,"bmi":0.06,"bp":-0.03,"s1":-0.02,"s2":0.03,"s3":-0.02,"s4":0.02,"s5":0.02,"s6":-0.001}' | grep 'prediction'
          docker logs svc
          docker rm -f svc
